import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import AppMenu from "@/components/AppMenu";
import MapDisplay from "@/components/MapDisplay";
import {useLoadScript} from "@react-google-maps/api";
import {Provider} from "react-redux";
import store from '@/redux/store';

const libraries = ['places'] as 'places'[]

export default function Home() {

  const {isLoaded} = useLoadScript({
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLEMAPS_APIKEY as string,
    libraries,
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Provider store={store}>
        <main className={styles.main}>
          {isLoaded && <AppMenu />}
          {isLoaded && <MapDisplay />}
        </main>
      </Provider>
    </>
  )
}
